### ISSUE TITLE
pod install失败

### ISSUE THREAD

**Issue by hanxiaofeng** [TheLittleBoy/HXRotationTool#1]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/10582931/221728323-462b16b5-61bd-4982-80f0-b329215fae0b.png">

**Comment by hanxiaofeng** [comment]
还有这个：

坑2、
调用完转屏方法以后，view需要重新更新frame，这时候你会发现获取到的屏幕宽高并不是你要转屏以后的结果。难道是在iOS 16中转屏不及时更新UIScreen的size了？ 可能是吧！这里我们就需要自己判断一下到底需要什么样的宽度和高度啦！

这个具体应该怎么处理呢，对ios不熟悉，麻烦指导下，非常感谢

**Comment by TheLittleBoy** [comment]
运行demo试试看，实践是检验真理的唯一标准！
我这里 pod 'HXRotationTool', '~> 0.3.0' 是可以。
你可能需要pod repo update一下。

**Comment by hanxiaofeng** [comment]
> 运行demo试试看，实践是检验真理的唯一标准！ 我这里 pod 'HXRotationTool', '~> 0.3.0' 是可以。 你可能需要pod repo update一下。

谢谢老哥，搞定了
